### PR TITLE
Enhance Oracle NoSQL Configuration

### PR DESCRIPTION
**Pull request by otaviojava**
# Changes

- Enhance documentation
- Increase the type of documentation

### CODE REVIEW

**Comment by dario-vega** [comment]
@otaviojava 

Is it possible to add/enhance support for the following authentication methods in DeploymentType.java?
- New `CLOUD_SECURITY_TOKEN ` [doc](https://oracle.github.io/nosql-java-sdk/oracle/nosql/driver/iam/SignatureProvider.html#createWithSessionToken())
```
SignatureProvider. createWithSessionToken();
SignatureProvider. createWithSessionToken (profileName);
SignatureProvider. createWithSessionToken (configFile, profileName);
```

- For `CLOUD_API_KEY`, there are several options [doc](https://oracle.github.io/nosql-java-sdk/oracle/nosql/driver/iam/SignatureProvider.html#%3Cinit%3E()):
  - Using information passed programmatically (**done**)
  - Using a configuration file - add the following options to the existing one 
 ```
new SignatureProvider(); // <<- this one exists in DeploymentType.java
new SignatureProvider(profileName);
new SignatureProvider(configFile, profileName);
```

**Comment by otaviojava** [comment]
> * doc

Hey, @dario-vega done.
Please let me know if it is missing something.

**Comment by dario-vega** [comment]
@otaviojava 

it is perfect for `CLOUD_SECURITY_TOKEN` but I didn't see support for `CLOUD_API_KEY` with the parameters `profileName` and `configFile`.

Current code for DeploymentType.java

```
 1 CLOUD_API_KEY { 
 2       @Override
 3        public Optional<AuthorizationProvider> apply(Settings settings) {
 4           if(user != null && password.length > 0 && tenantId != null && fingerprint != null && privateKey != null) {
 5                return Optional.of(new SignatureProvider(tenantId, user, fingerprint, privateKey, password));
 6            }
 7            try {
 8                return Optional.of(new SignatureProvider());
 9            } catch (IOException e) {
10               throw new OracleNoSQLException("Error to load configuration to Oracle Cloud at Oracle NoSQL", e);
11          }
12      }
13   },
```

We could modify **line 8**, to add support for `profileName` and `configFile `parameters

```
               if(profileName != null && configFile != null) {
                  return Optional.of(new SignatureProvider(configFile, profileName));
               } else if(profileName != null) {
                  return Optional.of(new SignatureProvider(profileName));
               } else  {
                  return Optional.of(new SignatureProvider());
               }
````

In the file BeerTemplateIntegrationTest.java, If you change line 3 from `data(Map.of("name", "beer"))` to `data(Map.of("name", "beer",  "price", 50))`

```
1        Beer beer = Beer.builder()
2               .id(UUID.randomUUID().toString())
3                //.data(Map.of("name", "beer"))
4               .data(Map.of("name", "beer",  "price", 50))
5                .comments(List.of("comment1", "comment2"))
6                .crew(List.of(new Crew("Otavio")))
7                .build();
```

In my example, I have the following error when running queries
```
java.lang.UnsupportedOperationException: There is not supported convert[DefaultDocument[name=price, value=DefaultValue[value=50]], DefaultDocument[name=name, value=DefaultValue[value=beer]]] a not Map type.
    at org.eclipse.jnosql.communication.reader.MapTypeReferenceReader.getMap (MapTypeReferenceReader.java:93)
    at org.eclipse.jnosql.communication.reader.MapTypeReferenceReader.convert (MapTypeReferenceReader.java:66)
    at org.eclipse.jnosql.communication.TypeReferenceReaderDecorator.convert (TypeReferenceReaderDecorator.java:55)
    at org.eclipse.jnosql.communication.DefaultValue.get (DefaultValue.java:55)
    at org.eclipse.jnosql.mapping.reflection.DefaultGenericFieldMetadata.value (DefaultGenericFieldMetadata.java:46)
    at org.eclipse.jnosql.mapping.document.FieldConverter$4.convert (FieldConverter.java:115)
    at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.lambda$feedObject$5 (DocumentEntityConverter.java:158)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
    at java.util.HashMap$KeySpliterator.forEachRemaining (HashMap.java:1707)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
    at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.convertEntity (DocumentEntityConverter.java:221)
    at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.toEntity (DocumentEntityConverter.java:127)
    at org.eclipse.jnosql.mapping.document.DefaultDocumentEntityConverter$Proxy$_$$_WeldClientProxy.toEntity (Unknown Source)
    at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.lambda$executeQuery$7 (AbstractDocumentTemplate.java:230)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1625)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:575)
    at java.util.stream.AbstractPipeline.evaluateToArrayNode (AbstractPipeline.java:260)
    at java.util.stream.ReferencePipeline.toArray (ReferencePipeline.java:616)
    at java.util.stream.ReferencePipeline.toArray (ReferencePipeline.java:622)
    at java.util.stream.ReferencePipeline.toList (ReferencePipeline.java:627)
    at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepository.findAll (AbstractDocumentRepository.java:52)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.eclipse.jnosql.mapping.core.query.AbstractRepositoryProxy.lambda$invoke$0 (AbstractRepositoryProxy.java:139)
    at org.eclipse.jnosql.mapping.core.query.AbstractRepositoryProxy.unwrapInvocationTargetException (AbstractRepositoryProxy.java:201)
    at org.eclipse.jnosql.mapping.core.query.AbstractRepositoryProxy.invoke (AbstractRepositoryProxy.java:139)
    at org.eclipse.jnosql.databases.oracle.mapping.OracleDocumentRepositoryProxy.invoke (OracleDocumentRepositoryProxy.java:117)
    at jdk.proxy4.$Proxy67.findAll (Unknown Source)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke (AbstractBeanInstance.java:38)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke (ProxyMethodHandler.java:106)
    at org.jnosql.demo.se.BeerRepository$1339028279$Proxy$_$$_WeldClientProxy.findAll (Unknown Source)
    at org.jnosql.demo.se.App.main (App.java:31)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:842)
```

**Comment by otaviojava** [comment]
> .data(Map.of("name", "beer",  "price", 50))

Thank you, @dario-vega I found this fix at the reader.

Now ready to go.
Could you let me know if I am missing something?

**Comment by dario-vega** [comment]
@otaviojava 

What about this? Is it possible to have support for `CLOUD_API_KEY` with the parameters `profileName` and `configFile` ?

Current code for DeploymentType.java

```
 1 CLOUD_API_KEY { 
 2       @Override
 3        public Optional<AuthorizationProvider> apply(Settings settings) {
 4           if(user != null && password.length > 0 && tenantId != null && fingerprint != null && privateKey != null) {
 5                return Optional.of(new SignatureProvider(tenantId, user, fingerprint, privateKey, password));
 6            }
 7            try {
 8                return Optional.of(new SignatureProvider());
 9            } catch (IOException e) {
10               throw new OracleNoSQLException("Error to load configuration to Oracle Cloud at Oracle NoSQL", e);
11          }
12      }
13   },
```

We could modify line 8, to add support for profileName and configFile parameters

```
               if(profileName != null && configFile != null) {
                  return Optional.of(new SignatureProvider(configFile, profileName));
               } else if(profileName != null) {
                  return Optional.of(new SignatureProvider(profileName));
               } else  {
                  return Optional.of(new SignatureProvider());
               }

```

**Comment by otaviojava** [comment]
> CLOUD_API_KEY

It is there, I will merge and generate a new version to you test.

**Pull request merged**
